builds:
  - id: "plugin"
    binary: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}.so"
    goos:
      - darwin
      - linux
    goarch:
      - arm64
      - amd64
    env:
      - CGO_ENABLED=1
    buildmode: plugin
    no_main_check: true

release:
  prerelease: auto

checksum:
  name_template: 'checksums.txt'
