builds:
  - id: "plugin"
    binary: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}.so"
    buildmode: plugin
    no_main_check: true

release:
  prerelease: auto

checksum:
  name_template: 'checksums.txt'
